dashpay/dips

- dip-0001.md
> Darren tapp patch 3

- README.md
- dip-0001.md
Per the [BIP 2 guidelines](https://github.com/bitcoin/bips/blob/master/bip-0002.mediawiki#progression-to-final-status), I believe this is now a candidate for promotion to "Final" status.
> promote DIP 0001 status to final

- dip-0002-special-transactions.md
- dip-0002.md
- dip-0003-masternode-types.md
- dip-0003.md
- dip-0004.md
Adds DIPs 2 through 4 and associated annex files
> DIP 2, 3, and 4 addition

- README.md
- dip-0006.md
- dip-0007.md
* add DIPs to the table in README
* remove H1 titles in DIPs
> small cleanup of new DIPs 6, 7

- dip-0005.md
> DIP5 - Standardize Sig field names with DIP3

- dip-0003.md
- dip-0004.md
Trying to make this as generic and non-C++-specific as possible. I'd like to wait 'til #26 is merged and I will rebase to resolve conflicts.
> swap vector type with generic list symbols

- dip-0004.md
Based upon #27 , which should be merged first
> DIP4: add size fields for following var len fields

- dip-0004.md
See https://github.com/dashpay/dash/pull/2440
> Add confirmedHash to SML entries

- dip-0005.md
Fixes SubTxCloseAccount payload detail table
> DIP5 - Correct markdown table layout

- dip-0002-special-transactions.md
- dip-0004.md
- dip-0006.md
- dip-0007.md
See individual commits. These are mostly updates so that the DIPs match the implementation.
> Multiple updates regarding LLMQs

- README.md
- dip-0002.md
- dip-0003.md
- dip-0004.md
- dip-0006.md
- dip-0007.md
- dip-0008.md
Update Readme and DIPs to reflect current status of DIPs 2-4 and 6-8
> Status update

- README.md
- dip-0010.md
[View DIP10](https://github.com/dashpay/dips/blob/d1b8bd58ef0bc90cefdf5f6714c90b682337dfd1/dip-0010.md)
> Add DIP10 - LLMQ-based InstantSend

- README.md
- dip-0009.md
- dip-0009/assignments.md
Informational DIP related to derivations paths for specific features
[View DIP-9](https://github.com/dashpay/dips/blob/096ead52d46222073107acbb1814d54f4765b00b/dip-0009.md)
> Add DIP9 - Feature derivation paths

- dip-0003.md
- dip-0006.md
- dip-0006/bls_signature_scheme.md
- dip-0007.md
- dip-0008.md
- dip-0010.md
Please see individual commits.
> A few (mostly trivial) updates

- dip-0006.md
Renames the test LLMQ and adds the new devnet one per Dash Core 0.16.0
Related to dashpay/dash#3269 and dashpay/dash#3348
> chore: update LLMQ table

- dip-0006.md
Changed the tense used in Motivation to make more sense.
> Update dip-0006 tense in motivation

- README.md
- dip-0011.md
- dip-0011/identity.json
- dip-0011/identityCreateTransition.json
- dip-0011/identityDisableTransition.json
- dip-0011/identityPublicKey.json
- dip-0011/identityTopUpTransition.json
- dip-0011/identityUpdateTransition.json
- dip-0012.md
This PR introduces the Dash Platform Identity and DPNS DIPs
> DIPs 11 (Identity) and 12 (DPNS)

- README.md
- dip-0005.md
Also includes a note to clarify why the status was changed
> Update DIP-5 status to minimize potential confusion

- dip-0007.md
> Fixed typo in link

- dip-0010.md
This is in line with the document it links to
> Trivial: Adjust Capitalization in DIP 10

- dip-0006.md
> Add LLMQ 100_67 to DIP6 table

- dip-0014.md
> DIP14: change threshold bits to >=2^32

- dip-0015.md
> DIP-15 specific extendedPublicKey serialization

- dip-0015.md
> DIP-15 specify HMAC hashing algorithm to be SHA256

- dip-0014.md
Add serialization test vectors to DIP14 for xprivkey and xpubkey.
> DIP14: add serialization test vectors

- README.md
These two DIPs have been implemented/activated and can be considered Final.
> docs: update status

- dip-0024.md
- dip-0024/dip-0024-addendum-parameter-choices.md
This addendum explains the security considerations behind [DIP-24](../dip-0024.md) in more detail.
> DIP24: add parameter choices addendum

- dip-0003-masternode-types.md
- dip-0003.md
- dip-0004.md
- dip-0006.md
- dip-0006/llmq-types.md
Need to merge first [#5021](https://github.com/dashpay/dash/pull/5021 ) and eventually release v19 before merging this.
> docs(llmq): v19 changes in DIPs

- README.md
- dip-0028.md
DIP-0028 needs to be aligned with implementation (https://github.com/dashpay/dash/pull/5508)
> refactor: `hpmn` rename to `evo` for DIP-0028

- README.md
- dip-0029.md
This DIP proposes leveraging DVRFs (Decentralized [Verifiable Random Functions](https://en.wikipedia.org/wiki/Verifiable_random_function)) to create decentralized randomness inside the Dash ecosystem in a secure, verifiable manner.
Preview: https://github.com/dashpay/dips/blob/dip29-random-beacon/dip-0029.md
> docs(DIP29): random beacon for llmq selection

- dip-0004.md
Added changes brought by DIP-29 and DIP-27 to Coinbase.
> chore: DIP4 Adjusted Coinbase description to v20

- dip-0002/special-transactions.md
Update status and version fields
> docs(dip2): update special transactions table

- dip-0027.md
Bumping the limit for the upcoming version.
> feat: bump withdrawals limit in DIP0027 to 4k
