dashpay/dips

dip-0001.md

bit1 corresponds to 0x20000002
https://github.com/bitcoin/bips/blob/master/bip-0009.mediawiki#specification
NOTE: bit0 (0x20000001) was used recently for deployment of BIP68, BIP112, and BIP113 and can't be re-used yet

fix bit1 hex representation/description

---

dip-0006.md

Thanks to @strophy for pointing this out.

fix typo in dip6 (make 'connection' plural)

---

dip-0005.md

This change proposes to remove non-alphanumeric characters for the first mainnet release of DIP 0005 Blockchain Users, with the option to add them in later.
The reasoning is based on securing future compatibility when integrating with global name based systems outside of the Dash protocol:
- Periods (.) are compatible with email but will complicate DNS records using BU names, for example user evan.duffield.xyz.tld requires 2 subdomains for a single BU, whereas evanduffield.xyz.tld requires 1 subdomain per BU
- Underscores (_) are not compatible with DNS.  They could be translated to hyphens (-) but this would complicate the implementation and is not a clean solution
- We could implement hyphens (-) but this would break email compatibility
- Adding these non-alphanumeric characters at …

DIP-0005: Removing non-alphanumeric characters

---

dip-0003.md

I was pretty concerned about the future migration process lately, especially about handling of DMNs without having HW wallet support for special txes, so I gave it yet another thought and propose to change DIP3 in a way that splits funds handling and DMN registration process. While this might sound like a step backwards (because it indeed looks a lot like an on-chain `mnb`-like thing now), IMO this approach has quite a few major advantages over the one currently described in DIP3:
1. no need to move collaterals to register existing masternodes as deterministic ones (or to re-register DMNs for some reasons);
2. no need to implement/update HW wallet firmware to support new types of Dash-specific transactions.
Not requiring to move collaterals should make migration less stressful in general. …

Separate creation/movement of MN collateral and DMN registration process

---

dip-0004.md

Added `merkleHashCount` and `merkleFlagsCount` to DIP4 simplified masternode list diff. These fields indicate the number of Merkle hashes and Merkle flags in the tree, respectively.

Mention `merkleHashCount` and `merkleFlagsCount` in DIP4

---

dip-0003.md
dip-0004.md
dip-0005.md
dip-0006.md
dip-0006/bls_signature_scheme.md
dip-0007.md

See individual commits.
Closes #23

Update DIPs regarding use of BLS12-381-reversed

---

dip-0003.md

This change is required to support HW wallets. These allow only signing of arbitrary text messages and not by hash.

Add description of collateralOutpoint and signing of ProRegTx

---

dip-0001.md

Image path in markdown was incorrect. It began with a `/` which is, of course, root. Path should be relative. I made it relative to the document. -t0dd (aka taw00)

fix broken image path in dip-001

---

dip-0006.md

Aligns the DIP with the Dash Core implementation details referenced in the issue.
Closes #36

[DIP6] Add llmqTypes details to qfcommit

---

dip-0008.md

See individual commits.
Please note that this already links to DIP10 (LLMQ based InstantSend), even though we don't have it in Github yet.

Multiple updates to DIP8

---

dip-0010.md

The fences aren't actually necessary, but make it easier (IMO) to delineate the
code block and not worry about number of leading spaces.
Previous to this the bottom code snippet was only rendering as code up to the newline, and the final part (`prevTxOut2, ...)` was displayed as normal (non-code) text.

Fix rendering of code block and use fenced blocks

---

README.md
dip-0006.md
dip-0007.md
dip-0008.md
dip-0010.md

LLMQ InstantSend has been active for nearly a month now, I assume it can be set to Final to avoid causing confusion.

Changed Status from 'Proposed' to 'Final'

---

dip-0001.md
dip-0002.md
dip-0003.md
dip-0004.md
dip-0005.md
dip-0006.md
dip-0007.md

Admin fix to update some of the earlier DIP copyrights. They will now match the more recent ones that are already correctly associated with the network-owned DCG.

fix: correct copyright name in DIPs 1-7

---

dip-0012/dpns-contract-documents.json

The DIP links to the file being added [here](https://github.com/dashpay/dips/blob/master/dip-0012.md#data-contract-document-schema). It was missing from the initial PR.

docs(dip-12): add missing file

---

dip-0006.md

c789750 See [quorums_dkgsession.h#L129](https://github.com/dashpay/dash/blob/43d2973a0e89ac9435142d6379e664c0ec20b2a2/src/llmq/quorums_dkgsession.h#L129) and [quorums_dkgsession.h#L141](https://github.com/dashpay/dash/blob/43d2973a0e89ac9435142d6379e664c0ec20b2a2/src/llmq/quorums_dkgsession.h#L141)
206a3c7 See [quorums_dkgsession.h#43](https://github.com/dashpay/dash/blob/43d2973a0e89ac9435142d6379e664c0ec20b2a2/src/llmq/quorums_dkgsession.h#L43) and [quorums_dkgsession.h#L54](https://github.com/dashpay/dash/blob/43d2973a0e89ac9435142d6379e664c0ec20b2a2/src/llmq/quorums_dkgsession.h#L54) which has the iv here [bls_ies.h#L86](https://github.com/dashpay/dash/blob/43d2973a0e89ac9435142d6379e664c0ec20b2a2/src/bls/bls_ies.h#L86) and in serializations …

dip6: Some fixes in the DKG message tables

---

dip-0014.md

update version bytes to encode to expected base58 chars, closes #80

DIP14: fix 256-bit version bytes

---

dip-0002-special-transactions.md
dip-0005.md

DIP5 was withdrawn earlier via https://github.com/dashpay/dips/pull/58

Remove DIP5 transaction types

---

README.md
dip-0021.md

This DIP documents changes introduced in Dash Core 0.17 that add two new P2P messages used to help masternodes recover DKG info and also support Platform features. Related Dash Core PRs are:
* [Implement P2P messages QGETDATA <-> QDATA](https://github.com/dashpay/dash/pull/3953)
* [Implement DKG data recovery / quorum verification vector
sync](https://github.com/dashpay/dash/pull/3964)
* [Add "mode" to -llmq-qvvec-sync parameter](https://github.com/dashpay/dash/pull/4030)
Thanks to @xdustinface for documenting this change.

DIP 21: LLMQ DKG Data Sharing

---

README.md

Aligns the README owners with the actual document authors

fix: correct list of DIP-15 owners in README

---

dip-0006.md

Add missing a `SHA256` (see https://github.com/dashpay/dips/pull/109#issuecomment-1100085671)

DIP6: correct mn list entry calculation

---

dip-0024.md

lastCommitmentPerIndex is an array of CFinalCommitment and not an array of uint256_t.

Correct type for lastCommitmentPerIndex

---

dip-0002-special-transactions.md

…table
It wasn't clear that the version in the table was the _payload_ version and not the _transaction_ version. See discussion in https://github.com/dashpay/dips/issues/35#issue-389036834 for context. Thanks @taw00 for bringing this up.
Closes #35

Dip2 table clarification

---

dip-0022.md

Currently DIP22 Choosing the active LLMQ to perform signing is partially wrong

dip22 referral fix regarding choosing quorum

---

dip-0010.md

Original wording can seem to indicate older blocks might also be ChainLocked. This is not the case, but it could have created issues so we're clarifying the wording to prevent confusion.

docs(dip-10): clarify retroactive lock

---

dip-0028.md

> The following new ProRegTx rules are added and are only applicable when `type` is 1:
those rules collide with some already existing rules (checking references to 1K) so the wording is not great but i'm not sure how to edit it here
platformNodeID is/represent the first....

chore: fix typo in DIP-28

---

README.md

These DIPs have been implemented and activated on mainnet already so they are moving from Proposed -> Final

chore: update DIP status in README.md

---

dip-0028.md

The original DIP didn't mentioned  rewards in the overview but didn't cover both stages (v19 / v20) in the actual masternode reward section. Relates to dashpay/dash-issues#38.

docs(dip28): add info to mn reward section

---

dip-0004.md

- Added minimum protocol version column.
- Decided to merge changes brought with protocol version `70214` since by now all clients should be up to date.
- Added changes brought by DIP-29 to `MNLISTDIFF`

chore: DIP4 mnlistdiff adjustment to newer protocol versions

---

README.md
dip-0002/special-transactions.md
dip-0011.md
dip-0027.md
dip-0027/dip-0027-request-id-calc.py
dip-0030.md

This DIP provides a mechanism for locking and unlocking Dash in a new store of value on the Core chain. The store of value, called the credit pool, mirrors the credit balance on Dash Platform. New special transactions enable locking Dash in the credit pool for use on Platform and unlocking it to withdraw back to Dash on the Core chain.

docs(dip27): dash core credit pool

---

dip-0027.md

Dash Core v22 makes simplifies withdrawal safety rules and also makes them less restrictive as implemented in dashpay/dash#6369.

docs(dip27): update withdrawal safety to match v22

---

README.md
dip-0031.md

To ensure that evonodes provide service on Dash Platform and that non-functioning evonodes do not participate in the Platform validator set, Platform needs a way to exclude faulty evonodes from future Platform validator sets / quorums. Since these nodes are not properly providing service, they should be proof-of-service (PoSe) banned. This DIP outlines a method for Platform to securely notify Core that a node should be banned.

docs(dip31): platform proof of service

---

.github/workflows/markdownlint.yml

Checks against the lint rules in https://github.com/dashpay/dips/blob/master/.markdownlint.json. Only checks changed files for now and "passes" even if lint identified.
Example run: https://github.com/thephez/dips/actions/runs/15164078202

ci: add lint action

---

dip-0006.md
dip-0014.md
dip-0021.md
dip-0023.md
dip-0024.md
dip-0025.md
dip-0026.md
dip-0029.md

Fix most lint (as identified by [.markdownlint.json](https://github.com/dashpay/dips/blob/master/.markdownlint.json)) in DIPs that are not currently undergoing edits. Duplicate headings were not modified. Using "Display rich diff", you can see that no visible changes are introduced by the updates.

docs: lint fixes

---

dip-0027.md

See discussion in https://github.com/dashpay/dash/pull/6662
Follow-up for https://github.com/dashpay/dips/pull/165

fix: the name of the hf to bump the withdrawals limit is `v23` now
